version: '3'
services:
  react-satu:
    container_name: react-satu
    build:
      context: .
    restart: always
    stdin_open: true
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - VIRTUAL_HOST=fe.bendo.local
      - VIRTUAL_PATH=/
      - VIRTUAL_PORT=3000

networks:
  jawak-network:
    external: true