version: "3"
services:
  nginx:
    image: nginx
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=bvt.test
      - NGINX_PORT=80
    networks:
      - jawak-network

networks:
  jawak-network:
    external: true